name: Deploy Firefox Add-on

# Trigger the workflow on push to the default branch
on:
  push:
    branches:
      - main  # Replace with your default branch if different (e.g., "master")

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Zip the addon
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r addon.zip addon

      - name: Upload Firefox Add-on
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: "{ad0f5919-f6bc-48be-809d-11cbf0f9dad9}"
          xpi-path: addon.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
